routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false, 'verify' => false, 'reset' => false,]);

Route::post('/login', 'Auth\LoginController@login');
Route::middleware(['auth'])->group(function() {
	Route::get('/querytsz/{tsz}','ConfigurationController@queryTsz');
	Route::get('/queryimei/{imei}','ConfigurationController@queryIMEI');
	Route::get('/querysim/{icc_tel}/{id}','ConfigurationController@querySim');
	Route::get('/queryaccessory','ConfigurationController@queryAccessory');

	Route::get('/filedownload', function (Request $request) {
		$utvonal = $request->input('utvonal');
		$fajlnev = $request->input('fajlnev');
		return response()->download(storage_path('app/' . $utvonal), $fajlnev);
	});
	Route::get('/showfile', function (Request $request) {
		$utvonal = $request->input('utvonal');
		$fajlnev = $request->input('fajlnev');
		return response()->file(storage_path('app/' . $utvonal));
	});
	Route::get('/delfile/{tipus}/{id}', function (Request $request, $tipus, $id) {
		switch ($tipus){
			case 'szamhordozas': $file = \App\SzamhordozasFajl::find($id);
				break;
			case 'konfiguracio':  $file = \App\Fajl::find($id);
				break;
		}
		if ($file && is_file(storage_path('app/' .$file->utvonal))){
			unlink(storage_path('app/' .$file->utvonal));
			$file->delete();
			return redirect()->back()
				->with('flash_message', 'Fájl törölve!');
		} else {
			return redirect()->back()
				->withErrors(['Fájl nem található!']);
		}
	})->middleware('permission:Fájlok törlése');
	Route::get('/suppliers/{id}/history','SupplierController@history')->name('suppliers.history');
	Route::get('/configurations/update_users','ConfigurationController@updateUsers');
	Route::get('/configurations/{id}/history','ConfigurationController@history')->name('configurations.history');
	Route::get('/configurations/query','ConfigurationController@query')->name('configurations.query');
	Route::get('/configurations/fetch_data', 'ConfigurationController@fetch_data');
	Route::get('/configurations/{id}/download', 'ConfigurationController@saveConfiguration')->name('configurations.download');	//download konfiguracio Word file with given id
	Route::get('/sims/masscreate','SimController@masscreate')->name('sims.masscreate');
	Route::post('/sims/csvimport','SimController@csvimport')->name('sims.csvimport');
	Route::get('/devices/masscreate','DeviceController@masscreate')->name('devices.masscreate');
	Route::post('/devices/csvimport','DeviceController@csvimport')->name('devices.csvimport');
	//Sim icc kódok szűkítése gépelés közben
	Route::get('/sims/fetch_data', 'SimController@fetch_data');
	Route::get('/devices/fetch_data', 'DeviceController@fetch_data');
	Route::get('/transfers/{id}/download', 'TransferController@downloadTransfer')->name('transfers.download');
	Route::get('/transfers/{id}/setready', 'TransferController@setReadyTransfer')->name('transfers.setready');
	Route::resources([
		'users' => 'UserController',
		'roles' => 'RoleController',
		'permissions' => 'PermissionController',
		'devices' => 'DeviceController',
		'suppliers' => 'SupplierController',
		'configurations' => 'ConfigurationController',
		'sims' => 'SimController',
		'types' => 'TypeController',
		'accessories' => 'AccessoryController',
		'transfers' => 'TransferController'
	]);
});

app/Accessory.php
<?php
/*
 * This file is part of the MobileCatalog Software package.
 *
 * @copyright 2021(c) KoRi <kovacsr@fkf.hu>
 *
 */

namespace App;

class Accessory extends BaseModel
{
	protected $table = 'mobile__accessories';
	public $timestamps = false;
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $guarded = [];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		//
	];

	/**
	 * The attributes that should be cast to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		//
	];

	public function beszallito()
	{
		return $this->belongsTo('App\Beszallito');
	}
	public function felhasznalo()
	{
		return $this->belongsTo('App\Felhasznalo')->withDefault([
			'nev' => 'nincs hozzárendelve',
			'tsz' => ''
		]);
	}
	public function konfig()
	{
		return $this->belongsTo('App\Konfiguracio');
	}
	public function statusz()
	{
		return $this->belongsTo('App\Statusz');
	}
}

app/Felhasznalo.php
<?php
/*
 * This file is part of the MobileCatalog Software package.
 *
 * @copyright 2021(c) KoRi <kovacsr@fkf.hu>
 *
 */

namespace App;

class Felhasznalo extends BaseModel
{

	protected $table = 'mobile__felhasznalo';
	public $timestamps = false;
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'nev', 'tsz', 'anyjaneve', 'lakcim', 'szuletesi_ido', 'szemigszam', 'koltseghely'
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		//
	];

	/**
	 * The attributes that should be cast to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		//
	];

	public function getNevTszAttribute()
	{
		return $this->nev.($this->tsz?' ('.$this->tsz.')':'');
	}
	public function eszkozok()
	{
		return $this->hasMany(\App\Mobileszkoz::class,'felhasznalo_id');
	}
	public function simek()
	{
		return $this->hasMany(\App\Sim::class,'felhasznalo_id');
	}
	public function konfigok()
	{
		return $this->hasMany(\App\Konfiguracio::class,'felhasznalo_id');
	}
}

app/Http/Controllers/AccessoryController.php
<?php
/*
 * This file is part of the MobileCatalog Software package.
 *
 * @copyright 2021(c) KoRi <kovacsr@fkf.hu>
 *
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Accessory;
use Response;

class AccessoryController extends Controller
{
	public function __construct() {
		//$this->middleware(['auth','permission:View devices']);
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$accessories = Accessory::paginate(200);
		return view('accessories.index')->with('accessories', $accessories);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('accessories.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$this->validate($request, [
			'nev'=>'required',
			'beszallito'=>'required',
			'ertek'=>'required',
			'datum'=>'required',
			'db' => 'required|numeric|min:1'
			]);
		for ($x=1;$x<=$request['db'];$x++){
			Accessory::create(['nev'=>$request['nev'], 'leltariszam' => $request['leltariszam'], 'megjegyzes' => $request['megjegyzes'], 'ertek' => $request['ertek'], 'datum' => $request['datum'], 'statusz_id' => $request['statusz'], 'beszallito_id' => $request['beszallito']]);
		}
		return redirect()->route('accessories.index')
			->with('flash_message', 'Kellék hozzáadva!');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id = car id
	 * @return \Illuminate\Http\Response
	 */
	public function show(Request $request, $id)
	{

	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$accessory = Accessory::where('id',$id)->firstOrFail();
		return view('accessories.edit')->with('accessory', $accessory);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$this->validate($request, [
			'nev'=>'required'
			]);
		Accessory::where('id',$id)->update(['nev' => $request['nev'], 'leltariszam' => $request['leltariszam'], 'megjegyzes' => $request['megjegyzes'], 'statusz_id' => $request['statusz']]);

		return redirect()->route('accessories.index')
			->with('flash_message', 'Kellék frissítve!');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{

	}
}

resources/views/accessories/create.blade.php
@extends('layouts.app')

@section('title', 'Új kiegészítő hozzáadása')

@section('accessories', 'active')
@section('db', 'active')

@push('head')
	<link href="{{ asset('css/bootstrap-datepicker3.min.css') }}"  rel="stylesheet">
	<script src="{{ asset('js/bootstrap-datepicker.min.js') }}" defer></script>
	<script src="{{ asset('js/bootstrap-datepicker.hu.min.js') }}" defer></script>
@endpush

@section('content')

<div class='col-xl-6 col-md-8 offset-xl-3 offset-md-2'>

    <h1><i class='fas fa-keyboard'></i> Új kiegészítő hozzáadása</h1>
    <br>

    <form action="{{ url('accessories') }}" method="POST">
        @csrf
		<div class="row">
			<div class="col-md-4 form-group">
				<label for="nev">Eszköz neve</label>
				<input type="text" id="nev" name="nev" class="form-control" value="{{old('nev')}}">
			</div>
			<div class="col-md-3 form-group">
				<label for="leltariszam">Leltáriszám</label>
				<input type="text" name="leltariszam" id="leltariszam" class="form-control" value="{{old('leltariszam')}}"  maxlength="6" onkeypress="return event.charCode >= 48 && event.charCode <= 57">
			</div>
			<div class="col-md-5 form-group">
				<label for="beszallito">Beszállító</label>
				<select class="custom-select" name="beszallito" id="beszallito">
					<option value="" selected disabled>Válassz beszállítót!</option>
					@foreach(\App\Beszallito::all() as $besz)
					<option value="{{$besz->id}}" {{ old('beszallito')==$besz->id?'selected':'' }}>{{$besz->partner}} ({{$besz->kontakt}})</option>
					@endforeach
				</select>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 form-group">
				<label for="megjegyzes">Megjegyzés</label>
				<input type="text" name="megjegyzes" id="megjegyzes" class="form-control" value="{{old('megjegyzes')}}" >
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 form-group">
				<label for="ertek">Érték (nettó)</label>
				<input type="text" name="ertek" id="ertek" class="form-control" value="{{ old('ertek') }}"  maxlength="6" onkeypress="return event.charCode >= 48 && event.charCode <= 57">
			</div>
			<div class="col-md-4 form-group">
				<label for="datum">Vásárlás dátuma</label>
				<input type="text" name="datum" id="datum" class="form-control" data-provide="datepicker" data-date-days-of-week-highlighted="6,0" data-date-today-highlight="true" data-date-max-view-mode="2" data-date-language="hu" data-date-autoclose="true" data-date-format="yyyy.mm.dd" value="{{ old('datum') }}" readonly="">
			</div>
			<div class="col-md-4 form-group">
				<label for="statusz_nev">Státusz</label>
				<input type="text" name="statusz_nev" id="statusz_nev" class="form-control" value="új-raktáron" readonly="">
				<input type="hidden" name="statusz" value="5">
			</div>
		</div>
        <br>
		<div class="d-flex justify-content-between">
			<div class="col-md-2 form-inline p-0">
				<label for="db">darabszám</label>
				<input type="text" name="db" id="db" class="col-4 form-control offset-1" value="{{ old('db')?old('db'):"1" }}" maxlength="2" onkeypress="return event.charCode >= 48 && event.charCode <= 57">
			</div>
			<button type="submit" class="btn btn-primary">Hozzáadás</button>
			<button type="button" class="btn btn-secondary" onclick="window.location='https://mobile.fkf.hu/accessories'">Mégse</button>		
		</div>

    </form>

</div>

@endsection

resources/views/accessories/edit.blade.php
@extends('layouts.app')

@section('title', 'Kiegészítő szerkesztése')

@section('accessories', 'active')
@section('db', 'active')

@section('content')

<div class='col-xl-6 col-md-8 offset-xl-3 offset-md-2'>

    <h1><i class='fa fa-keyboard'></i> Kiegészítő eszköz részletek </h1>
    <br>
    <form action="{{ route('accessories.update', $accessory->id) }}" method="POST">
        @method('PUT')
        @csrf
		<div class="row">
			<div class="col-md-4 form-group">
				<label for="nev">Eszköz neve</label>
				<input type="text" name="nev" class="form-control" value="{{$accessory->nev}}">
			</div>
			<div class="col-md-3 form-group">
				<label for="leltariszam">Leltáriszám</label>
				<input type="text" name="leltariszam" class="form-control" value="{{$accessory->leltariszam}}"  maxlength="6" onkeypress="return event.charCode >= 48 && event.charCode <= 57">
			</div>
			<div class="col-md-5 form-group">
				<label for="beszallito">Beszállító</label>
				<input type="text" name="beszallito" class="form-control" value="{{$accessory->beszallito->partner}}  ({{$accessory->beszallito->kontakt}})" readonly="readonly">
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 form-group">
				<label for="megjegyzes">Megjegyzés</label>
				<input type="text" name="megjegyzes" class="form-control" value="{{$accessory->megjegyzes}}" >
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 form-group">
				<label for="ertek">Érték (nettó)</label>
				<input type="text" name="ertek" class="form-control" value="{{ $accessory->ertek }}" readonly="readonly">
			</div>
			<div class="col-md-4 form-group">
				<label for="datum">Vásárlás dátuma</label>
				<input type="text" name="datum" class="form-control" value="{{ $accessory->datum }}" readonly="readonly">
			</div>
			<div class="col-md-4 form-group">
				<label for="statusz">Státusz</label>
				@can('Kiegészítő eszközök szerkesztése')
				<select class="custom-select" name="statusz">
					@foreach(\App\Statusz::all() as $stat)
					<option value="{{$stat->id}}" @if($accessory->statusz_id==$stat->id) selected @endif>{{$stat->nev}}</option>
					@endforeach
				</select>
				@else
				<input type="text" name="statusz_nev" class="form-control" value="{{$accessory->statusz->nev}}" readonly="">
				<input type="hidden" name="statusz" value="{{ $accessory->statusz_id }}">
				@endcan
			</div>
		</div>
        <br>
        <button type="submit" class="btn btn-primary" >Mentés</button>
        <button type="button" class="btn btn-secondary" onclick="window.location='{{ route('accessories.index')}}'">Vissza</button>

    </form>

</div>

@endsection

resources/views/accessories/index.blade.php
@extends('layouts.app')

@section('title', 'Kiegészítők')

@section('accessories', 'active')
@section('db', 'active')

@push('head')
	<script src="{{ asset('js/sorting.js') }}" defer></script>
@endpush

@section('content')

<div class="col-xl-8 offset-xl-2">
    <h1><i class="fas fa-keyboard"></i> Kiegészítő eszközök</h1>
    <hr>
	<div class="d-flex justify-content-between">
		<a href="{{ route('accessories.create') }}" class="btn btn-success mb-2">Új eszköz hozzáadása</a>
	</div>
	{{ $accessories->links() }}
    <div class="table-responsive filtertable">
        <table class="table table-bordered table-striped">

            <thead>
                <tr>
					<th><form class="form-inline"><label>Név</label><input type="search" class="form-control form-control-sm ml-auto txt-filter" data-filter="f-tipus" placeholder="Szűkítés..." /></form></th>
                    <th><form class="form-inline"><label>Leltári szám</label><input type="search" class="form-control form-control-sm ml-auto txt-filter" data-filter="f-lsz" placeholder="Szűkítés..." /></form></th>
					<th><form class="form-inline"><label>felhasználó</label><input type="search" class="form-control form-control-sm ml-auto txt-filter" data-filter="f-user" placeholder="Szűkítés..." /></form></th>
                    <th>Műveletek</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($accessories as $accessory)
                <tr>
                    <td class='f-tipus'>{{ $accessory->nev }}<br>{{ $accessory->megjegyzes?$accessory->megjegyzes:'' }}</td>
                    <td class='f-lsz'>{{ $accessory->leltariszam }}</td>
                    <td class='f-user'>{{ $accessory->felhasznalo->nev_tsz }}</td>
                    <td>
                    <a href="{{ route('accessories.edit', $accessory->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Részletek</a>
                    </td>
                </tr>
                @endforeach
            </tbody>

        </table>
    </div>
</div>

@endsection