routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false, 'verify' => false, 'reset' => false,]);

Route::post('/login', 'Auth\LoginController@login');
Route::middleware(['auth'])->group(function() {
	Route::get('/querytsz/{tsz}','ConfigurationController@queryTsz');
	Route::get('/queryimei/{imei}','ConfigurationController@queryIMEI');
	Route::get('/querysim/{icc_tel}/{id}','ConfigurationController@querySim');
	Route::get('/queryaccessory','ConfigurationController@queryAccessory');

	Route::get('/filedownload', function (Request $request) {
		$utvonal = $request->input('utvonal');
		$fajlnev = $request->input('fajlnev');
		return response()->download(storage_path('app/' . $utvonal), $fajlnev);
	});
	Route::get('/showfile', function (Request $request) {
		$utvonal = $request->input('utvonal');
		$fajlnev = $request->input('fajlnev');
		return response()->file(storage_path('app/' . $utvonal));
	});
	Route::get('/delfile/{tipus}/{id}', function (Request $request, $tipus, $id) {
		switch ($tipus){
			case 'szamhordozas': $file = \App\SzamhordozasFajl::find($id);
				break;
			case 'konfiguracio':  $file = \App\Fajl::find($id);
				break;
		}
		if ($file && is_file(storage_path('app/' .$file->utvonal))){
			unlink(storage_path('app/' .$file->utvonal));
			$file->delete();
			return redirect()->back()
				->with('flash_message', 'Fájl törölve!');
		} else {
			return redirect()->back()
				->withErrors(['Fájl nem található!']);
		}
	})->middleware('permission:Fájlok törlése');
	Route::get('/suppliers/{id}/history','SupplierController@history')->name('suppliers.history');
	Route::get('/configurations/update_users','ConfigurationController@updateUsers');
	Route::get('/configurations/{id}/history','ConfigurationController@history')->name('configurations.history');
	Route::get('/configurations/query','ConfigurationController@query')->name('configurations.query');
	Route::get('/configurations/fetch_data', 'ConfigurationController@fetch_data');
	Route::get('/configurations/{id}/download', 'ConfigurationController@saveConfiguration')->name('configurations.download');	//download konfiguracio Word file with given id
	Route::get('/sims/masscreate','SimController@masscreate')->name('sims.masscreate');
	Route::post('/sims/csvimport','SimController@csvimport')->name('sims.csvimport');
	Route::get('/devices/masscreate','DeviceController@masscreate')->name('devices.masscreate');
	Route::post('/devices/csvimport','DeviceController@csvimport')->name('devices.csvimport');
	//Sim icc kódok szűkítése gépelés közben
	Route::get('/sims/fetch_data', 'SimController@fetch_data');
	Route::get('/devices/fetch_data', 'DeviceController@fetch_data');
	Route::get('/transfers/{id}/download', 'TransferController@downloadTransfer')->name('transfers.download');
	Route::get('/transfers/{id}/setready', 'TransferController@setReadyTransfer')->name('transfers.setready');
	Route::resources([
		'users' => 'UserController',
		'roles' => 'RoleController',
		'permissions' => 'PermissionController',
		'devices' => 'DeviceController',
		'suppliers' => 'SupplierController',
		'configurations' => 'ConfigurationController',
		'sims' => 'SimController',
		'types' => 'TypeController',
		'accessories' => 'AccessoryController',
		'transfers' => 'TransferController'
	]);
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
	use HasRoles;

	protected $table = 'mobile__users';
	public $timestamps = false;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
		'name', 'username','email', 'password','last_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
		'password', 'remember_token','api_token','last_login',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        //'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

/*
 * This file is part of the MobileCatalog Software package.
 *
 * @copyright 2021(c) KoRi <kovacsr@fkf.hu>
 *
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
	public function __construct() {
		$this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a specific permission permission to access these resources
	}

	/**
	* Display a listing of the resource.
	*
	* @return \Illuminate\Http\Response
	*/
	public function index() {
		$users = User::orderBy('name')->get();
		return view('users.index')->with('users', $users);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		//
	}

	/**
	* Display the specified resource.
	*
	* @param  int  $id
	* @return \Illuminate\Http\Response
	*/
	public function show($id) {
		return redirect('users');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		$user = User::findOrFail($id); //Get user with specified id
		$roles = Role::get(); //Get all roles

		return view('users.edit', compact('user', 'roles')); //pass user and roles data to view
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		$user = User::findOrFail($id); //Get role specified by id
		$roles = $request['roles']; //Retreive all roles

		if (isset($roles)) {
			$user->roles()->sync($roles);  //If one or more role is selected associate user to roles
		}
		else {
			$user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
		}
		return redirect()->route('users.index')
			->with('flash_message', 'A felhasználó szerepköre sikeresen módosítva!');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		//
	}
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Felhasználó szerkesztése')

@section('content')

<div class='col-md-6 offset-md-3'>

    <h1><i class='fa fa-user'></i> {{$user->name}} szerkesztése</h1>
    <hr>
    <form action="{{ route('users.update', $user->id) }}" method="POST">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="username">Felhasználó név</label>
            <input type="text" name="username" class="form-control" readonly value="{{ $user->username }}" >
        </div>

        <h4><b>Szerepkör módosítás</b></h4>
		<h6><b>A SuperAdmin kivételével a többi szerepkör ideiglenesen állítható csak itt, címtárból visszaszinkronizál!</b></h6>

        <div class='form-group'>
            @foreach ($roles as $role)
            <input type="checkbox" name="roles[]" id="{{$role->name}}" value="{{$role->id}}" {{ $user->roles->contains('id',$role->id )?'checked':''}}>
            <label for="{{$role->name}}">{{ucfirst($role->name)}}<br></label><br>
            @endforeach
        </div>
        <button type="submit" class="btn btn-primary" >Mentés</button>
        <button type="button" class="btn btn-secondary" onclick="window.location='/users'">Mégse</button>

    </form>

</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Felhasználók')

@push('head')
	<script src="{{ asset('js/sorting.js') }}" defer></script>
@endpush

@section('content')

<div class="col-xl-8 offset-xl-2">
    <h1><i class="fa fa-users"></i> Felhasználó adminisztráció
	<a href="{{ route('roles.index') }}" class="btn btn-outline-secondary pull-right">Szerepkörök</a>
    <a href="{{ route('permissions.index') }}" class="btn btn-outline-secondary pull-right">Jogosultságok</a></h1>
    <hr>
    <div class="table-responsive filtertable">
        <table class="table table-bordered table-striped">

            <thead>
                <tr>
                    <th><form class="form-inline"><label>Név</label><input type="search" class="form-control form-control-sm ml-auto txt-filter" data-filter="f-nev" placeholder="Szűkítés..." /></form></th>
                    <th>Usernév</th>
                    <th>Utolsó bejelentkezés</th>
                    <th><form class="form-inline"><label>Felhasználó szerepkörei</label><input type="search" class="form-control form-control-sm ml-auto txt-filter" data-filter="f-role" placeholder="Szűkítés..." /></form></th>
                    <th>Műveletek</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($users as $user)
                <tr>

                    <td class='f-nev'>{{ $user->name }}</td>
                    <td>{{ $user->username }}</td>
                    <td>{{ $user->last_login }}</td>
                    <td class='f-role'>{{  $user->roles()->pluck('name')->implode(', ') }}</td>{{-- Retrieve array of roles associated to a user and convert to string --}}
                    <td>
                    <a href="{{ route('users.edit', $user->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Szerkeszt</a>
                    </td>
                </tr>
                @endforeach
            </tbody>

        </table>
    </div>

</div>

@endsection