routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false, 'verify' => false, 'reset' => false,]);

Route::post('/login', 'Auth\LoginController@login');
Route::middleware(['auth'])->group(function() {
	Route::get('/querytsz/{tsz}','ConfigurationController@queryTsz');
	Route::get('/queryimei/{imei}','ConfigurationController@queryIMEI');
	Route::get('/querysim/{icc_tel}/{id}','ConfigurationController@querySim');
	Route::get('/queryaccessory','ConfigurationController@queryAccessory');

	Route::get('/filedownload', function (Request $request) {
		$utvonal = $request->input('utvonal');
		$fajlnev = $request->input('fajlnev');
		return response()->download(storage_path('app/' . $utvonal), $fajlnev);
	});
	Route::get('/showfile', function (Request $request) {
		$utvonal = $request->input('utvonal');
		$fajlnev = $request->input('fajlnev');
		return response()->file(storage_path('app/' . $utvonal));
	});
	Route::get('/delfile/{tipus}/{id}', function (Request $request, $tipus, $id) {
		switch ($tipus){
			case 'szamhordozas': $file = \App\SzamhordozasFajl::find($id);
				break;
			case 'konfiguracio':  $file = \App\Fajl::find($id);
				break;
		}
		if ($file && is_file(storage_path('app/' .$file->utvonal))){
			unlink(storage_path('app/' .$file->utvonal));
			$file->delete();
			return redirect()->back()
				->with('flash_message', 'Fájl törölve!');
		} else {
			return redirect()->back()
				->withErrors(['Fájl nem található!']);
		}
	})->middleware('permission:Fájlok törlése');
	Route::get('/suppliers/{id}/history','SupplierController@history')->name('suppliers.history');
	Route::get('/configurations/update_users','ConfigurationController@updateUsers');
	Route::get('/configurations/{id}/history','ConfigurationController@history')->name('configurations.history');
	Route::get('/configurations/query','ConfigurationController@query')->name('configurations.query');
	Route::get('/configurations/fetch_data', 'ConfigurationController@fetch_data');
	Route::get('/configurations/{id}/download', 'ConfigurationController@saveConfiguration')->name('configurations.download');	//download konfiguracio Word file with given id
	Route::get('/sims/masscreate','SimController@masscreate')->name('sims.masscreate');
	Route::post('/sims/csvimport','SimController@csvimport')->name('sims.csvimport');
	Route::get('/devices/masscreate','DeviceController@masscreate')->name('devices.masscreate');
	Route::post('/devices/csvimport','DeviceController@csvimport')->name('devices.csvimport');
	//Sim icc kódok szűkítése gépelés közben
	Route::get('/sims/fetch_data', 'SimController@fetch_data');
	Route::get('/devices/fetch_data', 'DeviceController@fetch_data');
	Route::get('/transfers/{id}/download', 'TransferController@downloadTransfer')->name('transfers.download');
	Route::get('/transfers/{id}/setready', 'TransferController@setReadyTransfer')->name('transfers.setready');
	Route::resources([
		'users' => 'UserController',
		'roles' => 'RoleController',
		'permissions' => 'PermissionController',
		'devices' => 'DeviceController',
		'suppliers' => 'SupplierController',
		'configurations' => 'ConfigurationController',
		'sims' => 'SimController',
		'types' => 'TypeController',
		'accessories' => 'AccessoryController',
		'transfers' => 'TransferController'
	]);
});

app/Http/Controllers/RoleController.php
<?php

/*
 * This file is part of the MobileCatalog Software package.
 *
 * @copyright 2021(c) KoRi <kovacsr@fkf.hu>
 *
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller {

	public function __construct() {
		$this->middleware(['auth', 'isAdmin']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$roles = Role::orderBy('name')->get();//Get all roles

		return view('roles.index')->with('roles', $roles);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		$permissions = Permission::all();//Get all permissions

		return view('roles.create', ['permissions'=>$permissions]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
	//Validate name and permissions field
		$this->validate($request, [
			'name'=>'required|unique:'.config('permission.table_names.roles').'|max:30',
			'permissions' =>'required',
			]
		);

		$name = $request['name'];
		$role = new Role();
		$role->name = $name;

		$permissions = $request['permissions'];

		$role->save();
	//Looping thru selected permissions
		foreach ($permissions as $permission) {
			$p = Permission::where('id', '=', $permission)->firstOrFail();
		 //Fetch the newly created role and assign permission
			$role = Role::where('name', '=', $name)->first();
			$role->givePermissionTo($p);
		}

		return redirect()->route('roles.index')
			->with('flash_message', $role->name.' szerepkör hozzáadva!');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		return redirect('roles');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		$role = Role::findOrFail($id);
		$permissions = Permission::orderBy('name')->get();

		return view('roles.edit', compact('role', 'permissions'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {

		$role = Role::findOrFail($id);//Get role with the given id
	//Validate name and permission fields
		$this->validate($request, [
			'name'=>'required|max:30|unique:'.config('permission.table_names.roles').',name,'.$id,
			'permissions' =>'required',
		]);

		$input = $request->except(['permissions']);
		$permissions = $request['permissions'];
		$role->fill($input)->save();

		$p_all = Permission::all();//Get all permissions

		foreach ($p_all as $p) {
			$role->revokePermissionTo($p); //Remove all permissions associated with role
		}

		foreach ($permissions as $permission) {
			$p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
			$role->givePermissionTo($p);  //Assign permission to role
		}

		return redirect()->route('roles.index')
			->with('flash_message', $role->name.' szerepkör frissítve!');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		$role = Role::findOrFail($id);
		$role->delete();

		return redirect()->route('roles.index')
			->with('flash_message', 'Szerepkör törölve!');

	}
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('title', 'Szerepkör létrehozása')

@section('content')

<div class='col-md-6 offset-md-3 col-sm-8 offset-sm-2'>

    <h1><i class='fa fa-key'></i> Szerepkör létrehozása</h1>
    <hr>

    <form action="{{ url('roles') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Név</label>
            <input type="text" name="name" class="form-control" value="{{old('name')}}">
        </div>

        <h5><b>Jogosultság hozzárendelése</b></h5>

        <div class='form-group'>
            @foreach ($permissions as $permission)
                <input type="checkbox" name="permissions[]" value="{{$permission->id}}" >
                <label for="{{$permission->name}}">{{ucfirst($permission->name)}}</label><br>

            @endforeach
        </div>

        <button type="submit" class="btn btn-primary" >Hozzáadás</button>
        <button type="button" class="btn btn-secondary" onclick="window.location='{{ route('roles.index')}}'">Mégse</button>

    </form>

</div>

@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('title', 'Szerepkör szerkesztése')

@section('content')

<div class='col-md-6 offset-md-3 col-sm-8 offset-sm-2'>
    <h1><i class='fa fa-key'></i> Szerepkör szerkesztése: {{$role->name}}</h1>
    <hr>

    <form action="{{ route('roles.update', $role->id) }}" method="POST">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="name">Szerepkör neve</label>
            <input type="text" name="name" class="form-control" value="{{ $role->name }}">
        </div>

        <h5><b>Jogosultság hozzárendelése</b></h5>
        @foreach ($permissions as $permission)
            <input type="checkbox" name="permissions[]" value="{{$permission->id}}" {{ $role->permissions->contains('id',$permission->id )?'checked':''}}>
            <label for="{{$permission->name}}">{{ucfirst($permission->name)}}</label><br>
        @endforeach
        <br>
        <button type="submit" class="btn btn-primary" >Mentés</button>
        <button type="button" class="btn btn-secondary" onclick="window.location='{{ route('roles.index')}}'">Mégse</button>

    </form>
</div>

@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('title', 'Szerepkörök')

@push('head')
	<script src="{{ asset('js/sorting.js') }}" defer></script>
@endpush

@section('content')

<div class="col-xl-8 offset-xl-2">
    <h1><i class="fa fa-key"></i> Szerepkörök
    <a href="{{ route('users.index') }}" class="btn btn-outline-secondary pull-right">Felhasználók</a>
    <a href="{{ route('permissions.index') }}" class="btn btn-outline-secondary pull-right">Jogosultságok</a></h1>
    <hr>
    <a href="{{ URL::to('roles/create') }}" class="btn btn-success mb-2">Új szerepkör hozzáadás</a>
    <div class="table-responsive filtertable">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Szerepkör</th>
                    <th><form class="form-inline"><label>Jogosultság</label><input type="search" class="form-control form-control-sm ml-auto txt-filter" data-filter="f-jog" placeholder="Szűkítés..." /></form></th>
                    <th width="15%">Művelet</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($roles as $role)
                <tr>

                    <td>{{ $role->name }}</td>

                    <td class='f-jog'>{{ str_replace(array('[',']','"'),'', $role->permissions()->pluck('name')->toJson(JSON_UNESCAPED_UNICODE)) }}</td>{{-- Retrieve array of permissions associated to a role and convert to string --}}
                    <td>
                    <a href="{{ URL::to('roles/'.$role->id.'/edit') }}" class="btn btn-info pull-left" style="margin-right: 3px;">Szerkeszt</a>

                    <form action="{{ route('roles.destroy', $role->id) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-danger" >Töröl</button>
                    </form>
                    </td>
                </tr>
                @endforeach
            </tbody>

        </table>
    </div>
</div>

@endsection